@startuml
'https://plantuml.com/activity-diagram-beta
Title Carport

|Kunde|
start
:Indtast;
:Indsend forespørgsel;
|Mailsystem|
:Send forspørgsel til sælger;
|Sælger|
:Modtager forespørgsel]
|Beregningsystem|
:Indtaster stykliste;
|Lager|
:Henter stykliste;
|Beregningsystem|
:Stykliste]
:Beregner pris;
|Sælger|
:Stykliste + pris]
:Indsend prisoverslag;
|Mailsystem|
:Sender prisoverslag;
|Kunde|
:Prisoverslag]


if (Godkend pris?) then (ja)
:Betal;
else (nej)
        |Mailsystem|
        :Sender besked om afslag;
        |Sælger|
        :Kontakt kunden;
        endif

if (Betaling gennemført?) then (ja)
|Sælger|
:Modtager notifikation;
else (nej)
        |Sælger|
        :Kontakt kunden;
        endif

:Indsender faktura, stykliste + pris;
|Mailsystem|
:Sender faktura og stykliste;
|Kunde|
:Faktura + Stykliste]

stop

@enduml