@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana

object Customer {
name
email
password
address
phoneNumber
}

object Ordre {
ordre nr.
ordre name
Status paid
Total price
Date
}

object Seller {
email
password
}

object StyklisteFaktura {
materialInfo
ReceiptInfo
}

object materials {
Material nr
Material name
Material price
Material amount
}

Customer "1" *-- "M" Ordre
Seller "M" --* "M" Ordre
Ordre "1" *-- "M" StyklisteFaktura
StyklisteFaktura "M" *-- "M" materials


@enduml